version: '3.8'
services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    image: "web"
    container_name: "web"

    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - app

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    image: "flask"
    container_name: "flask"

    volumes:
      - type: bind
        source: "./app/src"
        target: "/var/www/src"
    ports:
      - 8000:8000
    expose:
      - 8000
